language: python

os:
  - "linux"
# - "osx"

python:
  - "2.7"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt
  - git clone https://github.com/bastikr/ubx-testdata.git

script:
  - python -m unittest discover test
