#!/usr/bin/env python

import argparse
import sys
import os

import ubx


argparser = argparse.ArgumentParser(description="Analyze a UBX stream")
argparser.add_argument("input", help="file or socket")
argparser.add_argument("--progress", help="show progress", action="store_true")

args = argparser.parse_args()

if ":" in args.input:
    raise NotImplementedError()
else:
    if not os.path.exists(args.input):
        raise ValueError("Given argument is neither a path nor a socket.")
    f = open(args.input, "rb")
    read_raw = f.read


stats = ubx.Statistics()


def read(n):
    stats.add_bytesread_try(n)
    result = read_raw(n)
    stats.add_bytesread_success(len(result))
    if args.progress:
        sys.stdout.write("Bytes read: {}\r".format(stats.bytes_read_success))
        sys.stdout.flush()
    return result


reader = ubx.Reader(read)
parser = ubx.default_parser


def run():
    while True:
        try:
            rawmessage = reader.read_rawmessage()
        except ubx.ChecksumError:
            stats.add_checksumerror()
            continue
        except EOFError:
            break
        else:
            stats.add_rawmessage(rawmessage)

        try:
            message = parser.parse(rawmessage)
        except KeyError:
            stats.add_unknownmessage(rawmessage)
            continue
        except ubx.PayloadError:
            stats.add_payloaderror(
                ubx.Message(parser.descriptions[rawmessage.key], None))
            continue
        else:
            stats.add_message(message)


try:
    run()
except KeyboardInterrupt:
    pass

if args.progress:
    sys.stdout.write(" " * 50 + "\r")
    sys.stdout.flush()

print(stats)
